FROM ghcr.io/tauffer-consulting/domino-airflow-pod:latest

# Install specific requirements
RUN apt update
RUN apt install ffmpeg -y

# Need to copy pieces source code
COPY config.toml domino/pieces_repository/
COPY pieces domino/pieces_repository/pieces
COPY .domino domino/pieces_repository/.domino

# Install specific python dependencies
RUN pip install --no-cache-dir youtube_dl
RUN pip install yt-dlp
RUN pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib